### ISSUE TITLE
Swap Service v0.1

### ISSUE THREAD

**Issue by okjodom** [bitsacco/os#1]
Scope: Build an automated swap service for on/offramp between a fiat currency and sats in fedimint. To start, this can only support on/offramp between KES/BTC. It should be extensible to other currency pairs. The actual integrations for conducting swap should be replaceable

## Milestones

- [x] define onramp api
   - [x] rpc service api : uses gRPC
   - [x] rest api: proxies the rpc api
- [x] implement onramp between kes/usd from mpesa
   - [x] using [Intasend](https://intasend.com)
   - [x] allow for intasend alternatives
- [x] implement offramp between kes/usd
- [x] package docker image for swap service
- [x] document api and usage
