### ISSUE TITLE
Chama Service v0.1

### ISSUE THREAD

**Issue by okjodom** [bitsacco/os#21]
Scope: Build a group (chama) savings service with support for spend conditions of the sats. This service should expect and integrate with a generic Swap Service, with which it can execute on/offramps. Chama service should also allow for "templates", a model by which different group savings can be built on the same base service

## Milestones

- [x] define chama api
   - [x] rpc service api : uses gRPC
   - [x] rest api: proxies the rpc api
- [ ] define generic chama tempate model
   - [ ] implement  a simple template model
   - [ ] allow extensibility of templates
- [x] package docker image for chama service
- [x] document api and usage
